//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPump
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> test_thoigian { get; set; }
        public Nullable<double> test_docao { get; set; }
        public Nullable<double> test_congsuat { get; set; }
        public Nullable<double> test_hieusuat { get; set; }
        public Nullable<double> test_khoiluong { get; set; }
        public string test_nguoi { get; set; }
        public string test_project { get; set; }
        public string test_model { get; set; }
        public string test_serialno { get; set; }
        public string test_ordernumber { get; set; }
        public string test_client { get; set; }
        public Nullable<double> test_motorpower { get; set; }
    }
}
